---
- hosts: all
  become: true
  vars:
    motd:
      - Ansible Managed Node by Seruelas, done on {{ inventory_hostname }}
  vars_prompt:
      - name: username
        prompt: Input your user name
        private: false
      - name: uid
        prompt: Input your own UID
        private: false

  tasks:

  - name: Banner MOTD
    ansible.builtin.debug:
      msg:
        - "{{ motd }}"

  - name: install python3 and pip3
    package:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes

  - name: install java open-jdk in Ubuntu
    apt:
        name:
          - openjdk-17-jdk
        state: latest
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install java open-jdk in CentOS
    yum:
      name:
        - java-11-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Create a user
    ansible.builtin.user:
      name: "{{ username }}"
      comment: NewUser
      uid: "{{ uid }}"
      createhome: yes
      home: /home/"{{ username }}"
      shell: /bin/bash


